#!/usr/bin/env php
<?php

use heinthanth\bare\Foundation\Console;

require_once __DIR__ . "/vendor/autoload.php";

$app = require_once __DIR__ . "/config/bootstrap.php";

$app->get(Console::class)->run();